#!/usr/bin/env bash
#script that installs nginx web server

sudo apt -y update
sudo apt -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo echo "Hello World!" | tee /var/www/html/index.nginx-debian.html
sudo service nginx start
sudo chown -R "$USER" /var/www/html
sudo chmod -R 755 /var/www
